import path from "node:path";
import { RENDERER_CATALOG_ID, RENDERER_CATALOG_VERSION } from "./showcase-values.mjs";

export function deriveRendererCatalog(showcases) {
  const toolsets = showcases.map((showcase) => Object.freeze({
    id: showcase.toolsetId,
    title: showcase.title,
    shortTitle: showcase.title,
    description: showcase.summary,
    tools: Object.freeze([]),
    metadata: Object.freeze({
      package: showcase.packageName,
      version: showcase.packageVersion,
    }),
  }));
  const activities = showcases.flatMap((showcase) => showcase.demos.map((demo) => Object.freeze({
    id: demo.activityId,
    toolsetId: showcase.toolsetId,
    title: demo.title,
    level: demo.level,
    summary: demo.summary,
    instructions: Object.freeze([demo.summary]),
    path: null,
    checkCount: demo.checkCount,
    metadata: Object.freeze({
      package: showcase.packageName,
      demo: demo.id,
      surface: demo.surface,
      tags: Object.freeze([...demo.tags]),
      theme: demo.theme,
      viewport: demo.viewport,
    }),
  })));
  const defaultActivity = showcases
    .flatMap((showcase) => showcase.demos)
    .find((demo) => demo.default) ?? activities[0] ?? null;
  const selectedActivityId = defaultActivity?.activityId ?? defaultActivity?.id ?? null;
  const selectedActivity = activities.find((activity) => activity.id === selectedActivityId) ?? activities[0] ?? null;
  const catalog = Object.freeze({
    id: RENDERER_CATALOG_ID,
    title: "Alumbra Renderer",
    version: RENDERER_CATALOG_VERSION,
    source: "greenways-ai/alumbra",
    surface: "activity",
    toolsets: Object.freeze(toolsets),
    activities: Object.freeze(activities),
    selectedToolsetId: selectedActivity?.toolsetId ?? null,
    selectedActivityId: selectedActivity?.id ?? null,
    capabilities: Object.freeze({
      selectToolset: true,
      selectActivity: true,
      insertTool: false,
      openActivity: true,
      checkActivity: true,
      resetActivity: true,
    }),
  });
  const installedDemos = Object.freeze(Object.fromEntries(showcases.flatMap((showcase) =>
    showcase.demos.map((demo) => [demo.activityId, Object.freeze({
      package: showcase.packageName,
      demo: demo.id,
      project: path.posix.join("packages", showcase.directoryName, demo.project),
      surface: demo.surface,
      host: demo.tags.includes("playable-lab") ? "playable-lab" : "showcase-project",
    })]))));
  return Object.freeze({ catalog, installedDemos });
}

function js(value) {
  return JSON.stringify(value, null, 2);
}

export function renderRendererCatalogModule(showcases) {
  const { catalog, installedDemos } = deriveRendererCatalog(showcases);
  return `// Generated by scripts/build-renderer-catalog.mjs. Do not edit.\n\n`
    + `const deepFreeze = (value) => {\n`
    + `  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;\n`
    + `  for (const entry of Object.values(value)) deepFreeze(entry);\n`
    + `  return Object.freeze(value);\n`
    + `};\n\n`
    + `export const ALUMBRA_RENDERER_CATALOG = deepFreeze(${js(catalog)});\n\n`
    + `export const ALUMBRA_RENDERER_INSTALLED_DEMOS = deepFreeze(${js(installedDemos)});\n\n`
    + `const CATALOG_OVERRIDE_KEYS = new Set([\n`
    + `  "id", "title", "selectedToolsetId", "selectedActivityId", "selectedToolId",\n`
    + `  "run", "metadata", "events",\n`
    + `]);\n\n`
    + `export function createAlumbraRendererCatalogArea(createCatalogArea, overrides = {}) {\n`
    + `  if (typeof createCatalogArea !== "function") {\n`
    + `    throw new TypeError("createAlumbraRendererCatalogArea requires Hodos createCatalogArea");\n`
    + `  }\n`
    + `  if (!overrides || typeof overrides !== "object" || Array.isArray(overrides)) {\n`
    + `    throw new TypeError("Alumbra Renderer Catalog overrides must be an object");\n`
    + `  }\n`
    + `  for (const key of Object.keys(overrides)) {\n`
    + `    if (!CATALOG_OVERRIDE_KEYS.has(key)) {\n`
    + `      throw new Error(\`Unsupported Alumbra Renderer Catalog override: \${key}\`);\n`
    + `    }\n`
    + `  }\n`
    + `  return createCatalogArea({\n`
    + `    id: "catalog/alumbra-renderer",\n`
    + `    title: "Renderer Catalog",\n`
    + `    catalogId: ALUMBRA_RENDERER_CATALOG.id,\n`
    + `    catalogTitle: ALUMBRA_RENDERER_CATALOG.title,\n`
    + `    version: ALUMBRA_RENDERER_CATALOG.version,\n`
    + `    source: ALUMBRA_RENDERER_CATALOG.source,\n`
    + `    surface: ALUMBRA_RENDERER_CATALOG.surface,\n`
    + `    toolsets: ALUMBRA_RENDERER_CATALOG.toolsets,\n`
    + `    activities: ALUMBRA_RENDERER_CATALOG.activities,\n`
    + `    selectedToolsetId: ALUMBRA_RENDERER_CATALOG.selectedToolsetId,\n`
    + `    selectedActivityId: ALUMBRA_RENDERER_CATALOG.selectedActivityId,\n`
    + `    capabilities: ALUMBRA_RENDERER_CATALOG.capabilities,\n`
    + `    ...overrides,\n`
    + `  });\n`
    + `}\n`;
}
